# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bdc6d10748ce4f0c8fe6ed5bbc17d7d5f19da646cdf83f365f78da6a27c1442b29298682dc6e40c3fc4bcd0e8b30c9efb8ac92e53d194e087be0e92d23976fed

test:
  secret_key_base: 4ed335cbbfe95ff589202f1f63498ed8c136dd65cf95f84c79f253b0f014fe5a84673cc56256b21b0dfe90c4112f8c331c43b9c7239fcffc150eddd7d781cb39

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
